# fly.toml file generated for nicegui-0-9 on 2022-12-12T19:52:01+01:00

app = "nicegui-0-9"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[build]
  image = "zauberzeug/nicegui:0.9.25"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = "20s"
    grace_period = "30s"
    method = "get"
    path = "/"
    protocol = "http"
    restart_limit = 1
    timeout = "2s"
    tls_skip_verify = false
    [services.http_checks.headers]